name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and tag the backend Docker image
      - name: Build and tag the backend Docker image
        working-directory: ./backend
        run: |
          docker build -t test/backend:latest .

  frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and tag the frontend Docker image
      - name: Build and tag the frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t test/frontend:latest .

