name: Build and Push to ACR
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Secrets (For Debugging Only)
        run: |
          echo "AZURE_URL: ${{ secrets.AZURE_URL }}"
          echo "ACR_USERNAME: ${{ secrets.ACR_USERNAME }}"
          echo "ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}"
          echo "IMAGE_TAG: ${{ secrets.IMAGE_TAG }}"

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.IMAGE_TAG }}
          file: Dockerfile
          platforms: linux/amd64
